web:
  image: web_web:latest
  environment:
    - SERVER_URLS=http://*:80
  expose:
    - "80"
lb:
  image: tutum/haproxy
  links:
    - web
  ports:
    - "80:80"
  environment:
    - BACKEND_PORT=80
    - BALANCE=roundrobin
